name: Publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Huawei Cloud Registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Log in to Huawei Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HUAWEI_CLOUD_REGISTRY_URL }}  # 华为云镜像仓库地址
          username: ${{ secrets.HUAWEI_CLOUD_REGISTRY_USERNAME }}  # 华为云镜像仓库用户名
          password: ${{ secrets.HUAWEI_CLOUD_REGISTRY_PASSWORD }}  # 华为云镜像仓库密码
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.HUAWEI_CLOUD_REGISTRY_URL }}/docker-common/nextchat  # 修改为华为云镜像仓库地址下的镜像名称
          tags: |
            type=raw,value=latest
            type=ref,event=tag
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
