name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ${{ secrets.HUAWEI_REGISTRY_URL }}
  IMAGE_NAME: docker-common/chatgpt-next-web  # 替换为你的组织/仓库名

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Huawei SWR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HUAWEI_REGISTRY_URL }}
          username: ${{ secrets.HUAWEI_REGISTRY_USERNAME }}
          password: ${{ secrets.HUAWEI_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

